---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChartGroup
metadata:
  layeringDefinition:
    abstract: false
    layer: global
  name: openstack-tenant-ceph
  namespace: shipyard
spec:
  chart_group:
  - tenant-ceph-ingress
  - tenant-ceph-mon
  - tenant-ceph-osd
  - tenant-ceph-client
  - tenant-ceph-config
  description: Ceph Storage
  sequenced: true
