---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChartGroup
metadata:
  layeringDefinition:
    abstract: false
    layer: global
  name: ucp-divingbell
  namespace: shipyard
spec:
  chart_group:
  - ucp-divingbell
  description: Divingbell
