---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChartGroup
metadata:
  layeringDefinition:
    abstract: false
    layer: global
  name: openstack-radosgw
  namespace: shipyard
spec:
  chart_group:
  - tenant-ceph-rgw
  description: Deploy Radosgw
