---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChartGroup
metadata:
  layeringDefinition:
    abstract: false
    layer: global
  name: osh-infra-prometheus-openstack-exporter
  namespace: shipyard
spec:
  chart_group:
  - prometheus-openstack-exporter
  description: Prometheus OpenStack Exporter
