---
apiVersion: armada.airshipit.org/v1alpha1
kind: ArmadaChartGroup
metadata:
  layeringDefinition:
    abstract: false
    layer: global
  name: ucp-drydock
  namespace: shipyard
spec:
  chart_group:
  - ucp-maas
  - ucp-drydock
  description: Drydock
